#!/usr/bin/env python3
"""Mutation smoke test: proves the test suite can actually fail.

For each mutation below, one targeted bug is injected into the source (exact-text replace), the
project is rebuilt with the given preset, and the test suite is run. The mutation is "killed" if
the suite fails (or the build breaks the tests), "SURVIVED" if everything still passes - which
means a gap in the tests.  The source file is always restored afterwards.

Safety: a mutated source file must never be left behind (or committed). The tool therefore
  * refuses to run unless every file it mutates is clean in git (override: --allow-dirty),
  * keeps an on-disk backup of the file it is mutating and restores it on SIGTERM/SIGHUP/SIGINT,
  * repairs leftovers from a run that died without cleaning up (e.g. SIGKILL) on the next start,
  * verifies at the end that the mutated files are byte-identical to how it found them.

Usage:  tools/mutation_smoke.py [--preset debug] [--only SUBSTRING[|SUBSTRING...]] [--check] [--allow-dirty]
Exit status is non-zero if any mutation survives or does not build.

Add a mutation whenever a new subsystem lands: pick a plausible, subtle bug (off-by-one, wrong
mask, missing null check, aliasing) rather than something that fails to compile.
"""
import argparse
import pathlib
import re
import signal
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

# (name, file, old text, new text, preset the mutation needs or None for any)
MUTATIONS = [
    ("string_t: compare prefix without byte swap (little-endian order bug)",
     "src/types/string_t.h",
     "return __builtin_bswap32(v);", "return v;", None),
    ("string_t: equality ignores inlined tail bytes",
     "src/types/string_t.h",
     "return ta == tb;", "return true;", None),
    ("string_t: compare skips the bytes after the prefix",
     "src/types/string_t.h",
     "if (min_len > kPrefixLength) {", "if (false) {", None),
    ("date: civil-from-days month adjustment off by one",
     "src/types/date.cpp",
     "y -= m <= 2;", "y -= m < 2;", None),
    ("date: leap-year rule ignores the 400-year exception",
     "src/types/date.h",
     "return (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;",
     "return year % 4 == 0 && year % 100 != 0;", None),
    ("value: NaN no longer sorts after every other double",
     "src/types/value.cpp",
     "return an == bn ? 0 : (an ? 1 : -1);", "return an == bn ? 0 : (an ? -1 : 1);", None),
    ("validity: CountValid includes bits beyond `count` in the tail word",
     "src/vector/validity_mask.cpp",
     "const uint64_t tail_mask = (uint64_t{1} << (count & 63)) - 1;",
     "const uint64_t tail_mask = ~uint64_t{0};", None),
    ("arena: bump allocation ignores the requested alignment",
     "src/memory/arena.cpp",
     "const size_t aligned = AlignUp(offset_, alignment);", "const size_t aligned = offset_;",
     None),
    ("vector: Slice of a dictionary forgets to compose with the old selection",
     "src/vector/vector.cpp",
     "new_sel.Set(i, sel_[sel[i]]);", "new_sel.Set(i, sel[i]);", None),
    ("vector: Reset overwrites a buffer another vector still references",
     "src/vector/vector.cpp",
     "if (!data_ || data_.use_count() > 1 || data_->read_only() || data_->size() < needed) {",
     "if (!data_ || data_->read_only() || data_->size() < needed) {", None),
    ("vector: Copy keeps pointers into the source's string heap",
     "src/vector/vector.cpp",
     "out[i] = dst_heap->Add(in[s].view());", "out[i] = in[s];",
     None),
    ("validity: SetRangeValid last-word mask is off by one bit",
     "src/vector/validity_mask.cpp",
     "(uint64_t{1} << (end & 63)) - 1;", "(uint64_t{1} << (end & 63)) - 2;", None),
    ("vector: Copy memcpy fast path copies one element too few",
     "src/vector/vector.cpp",
     "std::memcpy(out, in + src_offset, count * sizeof(T));",
     "std::memcpy(out, in + src_offset, (count - 1) * sizeof(T));",
     None),
    ("vector: Copy forgets to mark overwritten NULL slots valid when the source has no NULLs",
     "src/vector/vector.cpp",
     "dst_validity.SetRangeValid(dst_offset, count);", "(void)0;", None),
    # ---- Phase 2: storage ----
    ("stats: Ge pruning becomes unsound (skips when max == constant)",
     "src/storage/column_stats.cpp",
     "case CompareOp::Ge: return vs_max > 0;", "case CompareOp::Ge: return vs_max >= 0;", None),
    ("stats: Lt pruning is needlessly timid (never skips when min == constant)",
     "src/storage/column_stats.cpp",
     "case CompareOp::Lt: return vs_min <= 0;", "case CompareOp::Lt: return vs_min < 0;", None),
    ("stats: min/max consider values hidden under NULLs",
     "src/storage/column_stats.cpp",
     "if (!validity.IsValid(i)) { continue; }",
     "if (false && !validity.IsValid(i)) { continue; }", None),
    ("column builder: buffer growth loses the last appended row",
     "src/storage/column_builder.cpp",
     "std::memcpy(grown->data(), data_->data(), count_ * type_.width());",
     "std::memcpy(grown->data(), data_->data(), (count_ - 1) * type_.width());", None),
    ("column builder: validity of grown mask loses 'valid' default for new rows",
     "src/vector/validity_mask.cpp",
     "std::memset(grown->data() + old_words * sizeof(uint64_t), 0xFF,",
     "std::memset(grown->data() + old_words * sizeof(uint64_t), 0x00,", None),
    ("segment: Scan hands out the next vector's data view",
     "src/storage/column_segment.cpp",
     "out.ReferenceFlat(data_views_[v], std::move(validity), heap_);",
     "out.ReferenceFlat(data_views_[v + 1 < data_views_.size() ? v + 1 : v], std::move(validity), heap_);",
     None),
    ("segment: Scan hands out the wrong validity window",
     "src/storage/column_segment.cpp",
     "ValidityMask::FromBuffer(validity_views_[v], kVectorSize);",
     "ValidityMask::FromBuffer(validity_views_[0], kVectorSize);", None),
    ("table: append forgets to invalidate the cached tail snapshot",
     "src/storage/table.cpp",
     "    tail_cache_.reset(); // safe: the caller holds the exclusive lock, so no Snapshot() is running\n", "",
     None),
    ("table: append splits chunks across groups using the wrong remainder",
     "src/storage/table.cpp",
     "const idx_t n = std::min(open_->max_rows() - open_->count(), chunk.size() - pos);",
     "const idx_t n = chunk.size() - pos;", None),
    ("table: scans ignore zone maps entirely (pruning never fires)",
     "src/storage/table.cpp",
     "if (g.column(f.column_index).stats().CanSkip(f.op, f.constant)) {", "if ((void)f, false) {", None),
    ("table: scans over-prune (skip groups whose zone map says 'maybe')",
     "src/storage/table.cpp",
     "if (g.column(f.column_index).stats().CanSkip(f.op, f.constant)) {",
     "if (!g.column(f.column_index).stats().CanSkip(f.op, f.constant)) {", None),
    ("catalog: names are no longer case-insensitive",
     "src/catalog/catalog.cpp",
     "[](unsigned char c) { return static_cast<char>(std::tolower(c)); });",
     "[](unsigned char c) { return static_cast<char>(c); });", None),
    ("vector: Reset reuses a read-only (segment-owned) buffer for writing",
     "src/vector/vector.cpp",
     "if (!data_ || data_.use_count() > 1 || data_->read_only() || data_->size() < needed) {",
     "if (!data_ || data_.use_count() > 1 || data_->size() < needed) {", None),
    ("table (tsan): concurrent Snapshot() calls race on the tail cache",
     "src/storage/table.cpp",
     "std::lock_guard<std::mutex> guard(tail_mutex_);", "", "tsan"),
    ("table (tsan): Append only takes a shared lock, racing with readers",
     "src/storage/table.cpp",
     "    std::unique_lock lock(mutex_);\n    AppendLocked(chunk);",
     "    std::shared_lock lock(mutex_);\n    AppendLocked(chunk);", "tsan"),
    # ---- Phase 3: SQL front end ----
    ("lexer: '--' comments are no longer recognised",
     "src/parser/lexer.cpp",
     "if (c == '-' && i + 1 < n && sql[i + 1] == '-') {", "if (c == '-' && i + 1 < n && sql[i + 1] == '#') {", None),
    ("lexer: doubled quotes inside string literals are not unescaped",
     "src/parser/lexer.cpp",
     "if (i + 1 < n && sql[i + 1] == '\\'') {", "if (i + 1 < n && sql[i + 1] == '#') {", None),
    ("lexer: uppercase exponent 'E' is not a number",
     "src/parser/lexer.cpp",
     "if (i < n && (sql[i] == 'e' || sql[i] == 'E')) {", "if (i < n && sql[i] == 'e') {", None),
    ("parser: AND no longer binds tighter than OR",
     "src/parser/parser.cpp",
     "while (Peek().IsKeyword(Keyword::AND)) {", "while (Peek().IsKeyword(Keyword::OR)) {", None),
    ("parser: BETWEEN does not consume its AND as part of the predicate",
     "src/parser/parser.cpp",
     "ExprPtr hi = ParseAdditive();", "ExprPtr hi = ParseOr();", None),
    ("parser: 'x NOT IN' parses as 'x IN'",
     "src/parser/parser.cpp",
     "negated = true;\n        }\n        if (AcceptKeyword(Keyword::BETWEEN)) {", "negated = false;\n        }\n        if (AcceptKeyword(Keyword::BETWEEN)) {", None),
    ("ast: printed string literals do not double their quotes",
     "src/parser/ast.cpp",
     "if (ch == '\\'')\n            out += '\\'';\n        out += ch;\n    }\n    out += '\\'';", "out += ch;\n    }\n    out += '\\'';", None),
    ("parser: unary minus is dropped",
     "src/parser/parser.cpp",
     "return Finish(std::make_unique<UnaryExpr>(t.pos, UnaryOp::Negate, std::move(child)), d);", "(void)d; return child;", None),
    # ---- Phase 3: types, evaluation ----
    ("cast: DOUBLE -> integer rounds half away from zero instead of half to even",
     "src/types/cast.cpp",
     "const double r = std::nearbyint(d);", "const double r = std::round(d);", None),
    ("cast: hex integer strings are parsed as decimal",
     "src/types/cast.cpp",
     "base = 16;", "base = 10;", None),
    ("cast: interval month arithmetic does not clamp to the end of the month",
     "src/types/cast.cpp",
     "const int nd = std::min(d, Date::DaysInMonth(ny, nm));", "const int nd = d;", None),
    ("value: doubles switch to scientific notation one decade too late",
     "src/types/value.cpp",
     "if (exponent >= -4 && exponent < 16) {", "if (exponent >= -4 && exponent < 17) {", None),
    ("string_ops: LIKE '_' consumes one byte instead of one UTF-8 character",
     "src/common/string_ops.cpp",
     "t += Utf8CharLength(text, t);\n            p++;", "t += 1;\n            p++;", None),
    ("string_ops: substring treats start 0 like start 1",
     "src/common/string_ops.cpp",
     "long long begin = start > 0 ? start - 1 : (start == 0 ? -1 : n + start);", "long long begin = start > 0 ? start - 1 : (start == 0 ? 0 : n + start);", None),
    ("eval: AND/OR do not short-circuit",
     "src/planner/scalar_eval.cpp",
     "if (!l.IsNull() && l.GetBoolean() == !is_and)\n            return l; // false AND _ / true OR _", "if (false)\n            return l;", None),
    ("eval: integer addition overflow is not detected",
     "src/planner/scalar_eval.cpp",
     "if (__builtin_add_overflow(a, b, &r))\n            Overflow(\"addition\", type, shown);", "r = static_cast<T>(a + b);", None),
    # ---- Phase 3: binder ----
    ("binder: a non-grouped column is accepted next to aggregates",
     "src/planner/binder.cpp",
     "if (e->kind == BoundKind::ColumnRef) {\n            Fail(ErrorCode::Binder,\n                 \"column \\\"\" + e->name", "if (false) {\n            Fail(ErrorCode::Binder,\n                 \"column \\\"\" + e->name", None),
    ("binder: USING keeps both copies of the joined column in `*`",
     "src/planner/binder.cpp",
     "out.scope.columns[left_width + ro].hidden = true;", "out.scope.columns[left_width + ro].hidden = false;", None),
    ("binder: ORDER BY defaults to NULLS FIRST",
     "src/planner/binder.cpp",
     "const bool nulls_first = oi.nulls == NullOrder::First;", "const bool nulls_first = oi.nulls != NullOrder::Last;", None),
    ("binder: string literals are no longer converted in comparisons",
     "src/planner/bind_expression.cpp",
     "if (convert_string_literals && IsVarcharConstant(*l) && r->type.id() != TypeId::Varchar) {", "if (false && IsVarcharConstant(*l) && r->type.id() != TypeId::Varchar) {", None),
    ("binder: BETWEEN lower bound becomes exclusive",
     "src/planner/bind_expression.cpp",
     "MakeComparison(OperatorKind::Ge, x->Clone(), std::move(lo), e.pos);", "MakeComparison(OperatorKind::Gt, x->Clone(), std::move(lo), e.pos);", None),
    ("binder: `/` is no longer forced to floating point",
     "src/planner/bind_expression.cpp",
     "if (op == OperatorKind::Div) { // `/` is always floating point, like DuckDB", "if (false) { // `/`", None),
    ("binder: INTERVAL subtraction adds instead",
     "src/planner/bind_expression.cpp",
     "const int64_t amount = e.op == BinaryOp::Sub ? -interval.amount : interval.amount;", "const int64_t amount = interval.amount;", None),
    ("binder: a negative LIMIT is accepted",
     "src/planner/binder.cpp",
     "if (v < 0)", "if (v < -1000)", None),
    # ---- Phase 3: bulk load, DML ----
    ("table: NOT NULL columns accept NULLs",
     "src/storage/table.cpp",
     "if (!u.IsValid(r)) {", "if (false) {", None),
    ("table: Merge discards the target's partial tail",
     "src/storage/table.cpp",
     "sealed_.push_back(open_->Seal());\n    }\n    open_.reset();", "}\n    open_.reset();", None),
    ("csv: CRLF line endings leave a carriage return in the last field (serial loader)",
     "src/io/csv_reader.cpp",
     "if (record.back() == '\\r') {\n            stripped.assign(record, 0, record.size() - 1);\n            text = &stripped;\n        }\n        [[maybe_unused]]",
     "if (false) {\n            stripped.assign(record, 0, record.size() - 1);\n            text = &stripped;\n        }\n        [[maybe_unused]]", None),
    ("csv: CRLF line endings leave a carriage return in the last field (parallel loader)",
     "src/io/csv_reader.cpp",
     "if (record.back() == '\\r') {\n                        stripped.assign(record, 0, record.size() - 1);\n                        text = &stripped;\n                    }\n                    if (!SplitRecord(",
     "if (false) {\n                        stripped.assign(record, 0, record.size() - 1);\n                        text = &stripped;\n                    }\n                    if (!SplitRecord(", None),
    ("csv: the header line is loaded as data",
     "src/io/csv_reader.cpp",
     "bool skipped_header = !options.header;", "bool skipped_header = true;", None),
    ("vector: Flatten of a dictionary drops the child's string heap (use-after-free)",
     "src/vector/vector.cpp",
     "        heap_ = child_->heap_;\n", "", "asan"),
    # ---- Phase 4: vectorized executor, operators, planner, optimizer ----------------------------
    ("executor: AND/OR decide on the wrong truth value, so the right side is skipped for the wrong rows",
     "src/execution/expression_executor.cpp",
     "ld[lv.Slot(i)] == !is_and", "ld[lv.Slot(i)] == is_and", None),
    ("executor: three-valued AND is FALSE only if both sides are",
     "src/execution/expression_executor.cpp",
     "inline int And3(int a, int b) noexcept {\n    if (a == 0 || b == 0)",
     "inline int And3(int a, int b) noexcept {\n    if (a == 0 && b == 0)", None),
    ("executor: LIKE prefix matcher demands a strictly longer string",
     "src/execution/expression_executor.cpp",
     "return s.size() >= text.size() && s.compare(0, text.size(), text) == 0;",
     "return s.size() > text.size() && s.compare(0, text.size(), text) == 0;", None),
    ("executor: integer addition overflow is never reported",
     "src/execution/expression_executor.cpp",
     "return __builtin_add_overflow(a, b, &out);", "return false;", None),
    ("executor: Select of a negated comparison does not flip the operator",
     "src/execution/expression_executor.cpp",
     "want ? e.op : Negated(e.op)", "want ? e.op : Negated(Negated(e.op))", None),
    ("executor: Select narrows AND/OR the wrong way round",
     "src/execution/expression_executor.cpp",
     "if (is_and == want) {", "if (is_and != want) {", None),
    ("executor: IS NULL in selection position selects the opposite rows",
     "src/execution/expression_executor.cpp",
     "const bool is_true = (!cv.Valid(i)) != e.flag;", "const bool is_true = (!cv.Valid(i)) == e.flag;", None),
    ("hashing: 0.0 and -0.0 hash differently",
     "src/execution/hashing.cpp",
     "} else if (x == 0.0) {", "} else if (false) {", None),
    ("hashing: NaNs hash by their payload bits",
     "src/execution/hashing.cpp",
     "if (std::isnan(x)) {", "if (false) {", None),
    ("chunk store: Gather forgets to mark NULL rows invalid",
     "src/execution/chunk_store.cpp",
     "dv.SetInvalid(i);", "(void)dv;", None),
    ("key index: a pending (not yet stored) key is compared against the stored rows",
     "src/execution/key_index.cpp",
     "(id < stored ? cmp.StoredEqualsInput(keys_, id, i)", "(id <= stored ? cmp.StoredEqualsInput(keys_, id, i)", None),
    ("key comparator: NULL keys compare equal even when they must not (joins)",
     "src/execution/key_index.cpp",
     "if (s_valid != i_valid || !nulls_equal_) {", "if (s_valid != i_valid) {", None),
    ("aggregates: an integer SUM whose exact total leaves BIGINT is returned wrapped, not reported",
     "src/execution/aggregate_state.cpp",
     "if (sum < std::numeric_limits<int64_t>::min() || sum > std::numeric_limits<int64_t>::max()) {",
     "if (false) {", None),
    ("aggregates: merging two integer SUM states overwrites the total instead of adding",
     "src/execution/aggregate_state.cpp",
     "static_cast<const SumIntState&>(src);\n        for (idx_t g = 0; g < n; g++) {\n            if (s.has_[g]) {\n                sums_[dst[g]] += s.sums_[g];",
     "static_cast<const SumIntState&>(src);\n        for (idx_t g = 0; g < n; g++) {\n            if (s.has_[g]) {\n                sums_[dst[g]] = s.sums_[g];", None),
    ("aggregates: AVG of no non-NULL input is NaN instead of NULL",
     "src/execution/aggregate_state.cpp",
     "if (counts_[first + i] > 0) {", "if (true) {", None),
    ("aggregates: MIN and MAX are swapped",
     "src/execution/aggregate_state.cpp",
     "(kMax ? Less<T>(static_cast<T>(values_[g]), v)", "(!kMax ? Less<T>(static_cast<T>(values_[g]), v)", None),
    ("aggregates: COUNT(x) counts NULLs",
     "src/execution/aggregate_state.cpp",
     "if (u.validity->AllValid()) {", "if (true) {", None),
    ("group table: a global aggregate has no group until it sees a row",
     "src/execution/group_table.cpp",
     "if (group_types_.empty()) {\n        DataChunk none;", "if (false) {\n        DataChunk none;",
     None),
    ("group table: the ungrouped fast path falls through into the hashed path (double counting)",
     "src/execution/group_table.cpp",
     "return;\n    }\n    ids_.resize(count);", "}\n    ids_.resize(count);", None),
    ("group table: merging tables drops the other table's aggregate states",
     "src/execution/group_table.cpp",
     "states_[a]->Combine(*other.states_[a], mapping.data(), n);", "(void)mapping;", None),
    ("hash aggregate: a thread's finished table is dropped in Combine",
     "src/execution/hash_aggregate.cpp",
     "g.locals.push_back(std::move(table));", ";", None),
    ("hash join: LEFT join does not remember which probe rows matched",
     "src/execution/hash_join.cpp",
     "st.matched[st.probe_rows[j]] = 1;", "(void)j;", None),
    ("hash join: SEMI and ANTI are swapped",
     "src/execution/hash_join.cpp",
     "const bool want_matched = join_type_ == PhysicalJoinType::Semi;",
     "const bool want_matched = join_type_ == PhysicalJoinType::Anti;", None),
    ("sort: NULLs go to the wrong end",
     "src/execution/sort.cpp",
     "return (a_null == keys_[k].nulls_first) ? -1 : 1;", "return (a_null != keys_[k].nulls_first) ? -1 : 1;", None),
    ("sort: DESC is ignored",
     "src/execution/sort.cpp",
     "if (keys_[k].descending) {", "if (false) {", None),
    ("sort: the serial sort is no longer stable",
     "src/execution/sort.cpp",
     "std::stable_sort(order_.begin(), order_.end(),\n                     [this](uint32_t a, uint32_t b) { return CompareRows(a, b) < 0; });",
     "std::sort(order_.begin(), order_.end(),\n                     [this](uint32_t a, uint32_t b) { return CompareRows(a, b) < 0; });", None),
    ("sort: the single-run fallback of the parallel sort is not stable",
     "src/execution/sort.cpp",
     "std::stable_sort(order_.begin(), order_.end(), less);", "std::sort(order_.begin(), order_.end(), less);", None),
    ("top-n: OFFSET is ignored when computing the end of the output range",
     "src/execution/sort.cpp",
     "static_cast<idx_t>(offset_) + static_cast<idx_t>(limit_)", "static_cast<idx_t>(limit_)", None),
    ("limit: the limit is not reduced by rows already emitted from earlier chunks",
     "src/execution/basic_operators.cpp",
     "take = std::min(take, *limit_ - s.emitted);", "take = std::min(take, *limit_);", None),
    ("limit: never reports Finished, so the source is read to the end",
     "src/execution/basic_operators.cpp",
     "return limit_ && s.emitted >= *limit_ ?", "return limit_ && s.emitted > *limit_ ?", None),
    ("planner: ORDER BY ... LIMIT no longer plans as a top-N",
     "src/execution/physical_planner.cpp",
     "if (limit.limit && child.kind == LogicalKind::Order) {", "if (false) {", None),
    ("planner: the residual of a RIGHT join keeps the unswapped column numbering",
     "src/execution/physical_planner.cpp",
     "return o < lw ? o + rw : o - lw;", "return o;", None),
    ("planner: the projection after a swapped RIGHT join reads the wrong columns",
     "src/execution/physical_planner.cpp",
     "exprs.push_back(BoundExpr::ColumnRef(rw + i, left.types[i], left.names[i]));",
     "exprs.push_back(BoundExpr::ColumnRef(i, left.types[i], left.names[i]));", None),
    ("planner: an equality with the sides reversed is not recognised as a hash key",
     "src/execution/physical_planner.cpp",
     "if (a_left && b_right) {", "if (a_left && b_right && false) {", None),
    ("optimizer: WHERE conjuncts of a RIGHT join are pushed to its padded (left) side",
     "src/planner/optimizer.cpp",
     "if (left_only && preserve_left) {", "if (left_only) {", None),
    ("optimizer: ON conjuncts of a RIGHT join are pushed into the preserved side",
     "src/planner/optimizer.cpp",
     "if (preserve_left && right_only) {", "if (right_only) {", None),
    ("optimizer: OR factoring keeps the remainder even when a branch is exactly the common part",
     "src/planner/optimizer.cpp",
     "if (!any_empty && rest) {", "if ((!any_empty || true) && rest) {", None),
    ("optimizer: OR factoring treats every conjunct of the first branch as common",
     "src/planner/optimizer.cpp",
     "in_all = std::any_of(branch_parts[b].begin(), branch_parts[b].end(),", "in_all = true || std::any_of(branch_parts[b].begin(), branch_parts[b].end(),", None),
    ("optimizer: zone-map hint ignores that the constant was on the left",
     "src/planner/optimizer.cpp",
     "op = Flip(op);", "op = Flip(Flip(op));", None),
    ("optimizer: HAVING conjuncts on aggregates are pushed below the aggregate",
     "src/planner/optimizer.cpp",
     "if (!refs.empty() && *refs.rbegin() < agg.groups.size()) {", "if (!refs.empty()) {", None),
    ("optimizer: LIMIT no longer moves below a projection (so never becomes a top-N)",
     "src/planner/optimizer.cpp",
     "if (op->children[0]->kind == LogicalKind::Projection) {", "if (false) {", None),
    # (the greedy ordering this mutant targeted was replaced in Phase 8; its composite-key rule now
    # lives in planner/join_order.cpp and planner/cardinality.cpp, mutated in the Phase 8 section)
    ("string_ops: a truncated multi-byte sequence is read past the end of the string",
     "src/common/string_ops.cpp",
     "if (len > s.size() - pos)", "if (false)", None),
    ("string_ops: a lead byte followed by a non-continuation byte still swallows it",
     "src/common/string_ops.cpp",
     "!= 0x80)", "== 0x80)", None),
    ("vector: Reset keeps a shared buffer instead of detaching (aliasing writes)",
     "src/vector/vector.cpp",
     "data_.reset(); // allocated on first write access (EnsureData): often there is none", ";", None),
    ("vector: ToUnified of a lazily allocated vector reads a null buffer",
     "src/vector/vector.cpp",
     "case VectorFormat::Flat:\n        EnsureData();\n        out.sel = SelectionVector::Identity().data();",
     "case VectorFormat::Flat:\n        out.sel = SelectionVector::Identity().data();", None),
    # ---- Phase 5: bit-packing, segment encodings, SIMD kernels --------------------------------
    ("bitpacking: BitWidth is one too small",
     "src/storage/bitpacking.h",
     "64 - __builtin_clzll(x)", "63 - __builtin_clzll(x)", None),
    ("bitpacking: PackedBytes drops the slack word (unpack reads past the stream)",
     "src/storage/bitpacking.h",
     "/ 64) * 8 + 8;", "/ 64) * 8;", "asan"),
    ("bitpacking: BitUnpack of zero values passes null pointers to memset/memcpy",
     "src/storage/bitpacking.cpp",
     "if (count == 0) {", "if (false) {", "asan"),
    ("bitpacking: BitPack keeps the high bits of the input",
     "src/storage/bitpacking.cpp",
     "const uint64_t v = in[i] & mask;", "const uint64_t v = in[i] & (mask | ~mask);", None),
    ("bitpacking: the bit position after a word boundary is off by one",
     "src/storage/bitpacking.cpp",
     "used = used + width - 64;", "used = used + width - 63;", None),
    ("bitpacking: the generic tail unpack ignores values straddling two words",
     "src/storage/bitpacking.cpp",
     "if (shift + width > 64) {", "if (false) {", None),
    ("bitpacking: the unrolled unpacker shifts the straddling part by the wrong amount",
     "src/storage/bitpacking.cpp",
     "v |= w[word + 1] << (64 - shift);", "v |= w[word + 1] << (63 - shift);", None),
    ("bitpacking: the unrolled unpacker masks one bit too many",
     "src/storage/bitpacking.cpp",
     "constexpr uint64_t mask = W == 64 ? ~uint64_t{0} : (uint64_t{1} << W) - 1;",
     "constexpr uint64_t mask = W == 64 ? ~uint64_t{0} : (uint64_t{1} << W) * 2 - 1;", None),
    ("bitpacking: the unrolled unpacker reads each block one word late",
     "src/storage/bitpacking.cpp",
     "std::memcpy(words, in + (i / 64) * W * 8, W * 8);",
     "std::memcpy(words, in + (i / 64) * W * 8 + 8, W * 8);", None),
    ("encoding: delta chosen for a sequence that is not monotone",
     "src/storage/encoding.cpp",
     "monotone = false;", "monotone = true;", None),
    ("encoding: the first delta of a vector is not zero",
     "src/storage/encoding.cpp",
     "packed[0] = 0;", "packed[0] = 1;", None),
    ("encoding: frame-of-reference base is the first value instead of the minimum",
     "src/storage/encoding.cpp",
     "m.base = lo;\n            m.width = for_width;", "m.base = x[0];\n            m.width = for_width;",
     None),
    ("encoding: a constant bit-packed vector with NULL rows is returned as an all-valid constant",
     "src/storage/encoding.cpp",
     "if (m.width == 0 && !m.delta && validity.CountValid(n) == n) {",
     "if (m.width == 0 && !m.delta && validity.CountValid(n) <= n) {", None),
    ("encoding: an RLE vector covered by one run ignores its NULL rows",
     "src/storage/encoding.cpp",
     "if (ends_[run] >= end && validity.CountValid(n) == n) {", "if (ends_[run] >= end && validity.CountValid(n) <= n) {", None),
    ("encoding: RLE fill runs past the end of the vector",
     "src/storage/encoding.cpp",
     "const idx_t stop = std::min<idx_t>(ends_[run], end);", "const idx_t stop = ends_[run];", None),
    ("encoding: RLE remembers the wrong first run of a vector",
     "src/storage/encoding.cpp",
     "static_cast<uint32_t>(run_values.size() - 1)); // the run holding row i",
     "static_cast<uint32_t>(run_values.size())); // the run holding row i", None),
    ("encoding: a constant double vector with NULL rows is returned as an all-valid constant",
     "src/storage/encoding.cpp",
     "if (validity.CountValid(n) == n) {\n                out.SetConstant(Value::Double(d));",
     "if (validity.CountValid(n) <= n) {\n                out.SetConstant(Value::Double(d));", None),
    ("encoding: scaled doubles compare by value, so -0.0 turns into 0.0",
     "src/storage/encoding.cpp",
     "if (std::memcmp(&back, &v[i], sizeof(double)) != 0) {", "if (back != v[i]) {", None),
    ("encoding: constant detection compares doubles by value (0.0 == -0.0)",
     "src/storage/encoding.cpp",
     "} else if (std::memcmp(&v[i], &v[first], sizeof(double)) != 0) {",
     "} else if (v[i] != v[first]) {", None),
    ("encoding: offsets wider than 52 bits go through the exact-conversion trick",
     "src/storage/encoding.cpp",
     "if (m.width <= 52) {", "if (m.width <= 63) {", None),
    ("encoding: dictionary NULL rows map to the first entry",
     "src/storage/encoding.cpp",
     "packed[i] = row_code[start + i] == kNoCode ? null_code : row_code[start + i];",
     "packed[i] = row_code[start + i] == kNoCode ? 0 : row_code[start + i];", None),
    ("encoding: the dictionary's NULL entry is not marked invalid",
     "src/storage/encoding.cpp",
     "dictionary->Validity().SetInvalid(null_code);", "dictionary->Validity().SetInvalid(0);",
     None),
    ("encoding: a dictionary may fill every slot, leaving none for its NULL entry",
     "src/storage/encoding.cpp",
     "if (entries.size() == kVectorSize - 1) {", "if (entries.size() == kVectorSize) {", None),
    ("encoding: Auto accepts an encoding that saves nothing",
     "src/storage/encoding.cpp",
     "constexpr double kMaxEncodedFraction = 0.7;", "constexpr double kMaxEncodedFraction = 1e9;",
     None),
    ("encoding: the smallest candidate is no longer the one kept",
     "src/storage/encoding.cpp",
     "candidate->MemoryUsage() < best->MemoryUsage()",
     "candidate->MemoryUsage() > best->MemoryUsage()", None),
    ("segment: an encoded scan drops the segment's NULLs for non-constant vectors",
     "src/storage/column_segment.cpp",
     "if (!encoded_->DecodeVector(v, n, validity, out)) {",
     "if (encoded_->DecodeVector(v, n, validity, out)) {", None),
    ("segment: an encoded scan does not reset the reused output vector",
     "src/storage/column_segment.cpp",
     "if (encoded_ != nullptr) {\n        out.Reset();", "if (encoded_ != nullptr) {", None),
    ("simd: SetSimdEnabled(false) has no effect",
     "src/kernels/cpu.cpp",
     "SimdState().load(std::memory_order_relaxed) != 0 && CpuHasAvx2()",
     "SimdState().load(std::memory_order_relaxed) != 0 || CpuHasAvx2()", None),
    ("select kernel: the compaction table lists the positions in reverse order",
     "src/kernels/select.cpp",
     "perm[mask][k++] = bit;", "perm[mask][k++] = 7 - bit;", None),
    ("select kernel: the match count ignores the eighth lane",
     "src/kernels/select.cpp",
     "__builtin_popcount(mask)", "__builtin_popcount(mask & 0x7F)", None),
    ("select kernel: int32 <= excludes equality",
     "src/kernels/select.cpp",
     "case CmpOp::Le:\n            m = _mm256_xor_si256(_mm256_cmpgt_epi32(x, c), _mm256_set1_epi32(-1));",
     "case CmpOp::Le:\n            m = _mm256_cmpgt_epi32(c, x);", None),
    ("select kernel: int32 tail skips its first row",
     "src/kernels/select.cpp",
     "SelectScalar(op, data + 0, i, count, constant, out + n)",
     "SelectScalar(op, data + 0, i + 1, count, constant, out + n)", None),
    ("select kernel: int64 >= is a strict comparison",
     "src/kernels/select.cpp",
     "default: // Ge\n        return _mm256_xor_si256(_mm256_cmpgt_epi64(c, x), ones);",
     "default: // Ge\n        return _mm256_cmpgt_epi64(x, c);", None),
    ("select kernel: double > is false for NaN (NaN must be the largest value)",
     "src/kernels/select.cpp",
     "_CMP_NLE_UQ", "_CMP_GT_OQ", None),
    ("select kernel: double >= is false for NaN",
     "src/kernels/select.cpp",
     "_CMP_NLT_UQ", "_CMP_GE_OQ", None),
    ("select kernel: double != is false for NaN",
     "src/kernels/select.cpp",
     "_CMP_NEQ_UQ", "_CMP_NEQ_OQ", None),
    ("select kernel: a NaN constant reaches the vector comparison",
     "src/kernels/select.cpp",
     "if (UseAvx2() && !std::isnan(constant)) {", "if (UseAvx2()) {", None),
    ("decode kernel: scaled-double conversion uses the wrong magic exponent",
     "src/kernels/decode.cpp",
     "0x4330000000000000LL", "0x4320000000000000LL", None),
    ("decode kernel: scaled-double tail drops its last value",
     "src/kernels/decode.cpp",
     "OffsetsToScaledDoubleScalar(off + i, n - i, base, scale, out + i);",
     "OffsetsToScaledDoubleScalar(off + i, n - i - (n - i > 0 ? 1 : 0), base, scale, out + i);",
     None),
    ("aggregate kernel: int32 sum counts the low half of each register twice",
     "src/kernels/aggregate.cpp",
     "_mm256_extracti128_si256(v, 1)));\n    }\n    alignas(32) int64_t lanes[4];\n    _mm256_store_si256(reinterpret_cast<__m256i*>(lanes), acc);\n    return lanes[0]",
     "_mm256_extracti128_si256(v, 0)));\n    }\n    alignas(32) int64_t lanes[4];\n    _mm256_store_si256(reinterpret_cast<__m256i*>(lanes), acc);\n    return lanes[0]",
     None),
    ("aggregate kernel: a lane overflow is not reported",
     "src/kernels/aggregate.cpp",
     "_mm256_castsi256_pd(overflow)) != 0", "_mm256_castsi256_pd(overflow)) == 7", None),
    ("aggregate kernel: overflow while combining the four lanes is ignored",
     "src/kernels/aggregate.cpp",
     "if (__builtin_add_overflow(total, lane, &total)) {",
     "if ((void)__builtin_add_overflow(total, lane, &total), false) {", None),
    ("aggregate kernel: the double sum forgets one lane",
     "src/kernels/aggregate.cpp",
     "for (int lane = 0; lane < 8; lane++) {", "for (int lane = 0; lane < 7; lane++) {", None),
    ("aggregate kernel: int32 MIN takes the maximum",
     "src/kernels/aggregate.cpp",
     "lo = _mm256_min_epi32(lo, v);", "lo = _mm256_max_epi32(lo, v);", None),
    ("aggregate kernel: int64 MIN/MAX compare the wrong way round",
     "src/kernels/aggregate.cpp",
     "lo = _mm256_blendv_epi8(lo, v, _mm256_cmpgt_epi64(lo, v));",
     "lo = _mm256_blendv_epi8(lo, v, _mm256_cmpgt_epi64(v, lo));", None),
    ("hash kernel: the vector multiply loses the cross term's shift",
     "src/kernels/hash.cpp",
     "_mm256_slli_epi64(cross, 32)", "_mm256_slli_epi64(cross, 31)", None),
    ("hash kernel: combining uses the wrong multiplier",
     "src/kernels/hash.cpp",
     "Fmix(_mm256_add_epi64(Mul64(seed, kCombineK), h))",
     "Fmix(_mm256_add_epi64(Mul64(seed, kMurmurC1), h))", None),
    ("hash kernel: int32 keys are zero-extended instead of sign-extended",
     "src/kernels/hash.cpp",
     "_mm256_cvtepi32_epi64(_mm_loadu_si128", "_mm256_cvtepu32_epi64(_mm_loadu_si128", None),
    ("executor: `constant < column` is evaluated as `column < constant`",
     "src/execution/expression_executor.cpp",
     "case OperatorKind::Lt:\n        return OperatorKind::Gt;",
     "case OperatorKind::Lt:\n        return OperatorKind::Lt;", None),
    ("executor: comparison with a NULL constant selects every row",
     "src/execution/expression_executor.cpp",
     "matches = 0; // a comparison with NULL is never TRUE", "matches = n;", None),
    ("executor: the kernel selection keeps rows whose column value is NULL",
     "src/execution/expression_executor.cpp",
     "kept += v.Valid(out[j]);", "kept += 1;", None),
    ("aggregate: the vectorised path is taken for a vector with NULLs",
     "src/execution/aggregate_state.cpp",
     "return v != nullptr && v->format() == VectorFormat::Flat && v->Validity().AllValid()",
     "return v != nullptr && v->format() == VectorFormat::Flat", None),
    ("aggregate: ungrouped MIN/MAX returns the opposite extreme",
     "src/execution/aggregate_state.cpp",
     "Offer(0, kMax ? hi : lo);", "Offer(0, kMax ? lo : hi);", None),
    ("hashing: dictionary strings hash the first row's entry for every row",
     "src/execution/hashing.cpp",
     "const sel_t code = u.sel[i];", "const sel_t code = u.sel[0];", None),
    ("hashing: a NULL dictionary row hashes its (empty) entry instead of the NULL hash",
     "src/execution/hashing.cpp",
     "uint64_t h = kNullHash;\n                    if (u.IsValid(i)) {",
     "uint64_t h = kNullHash;\n                    if (true) {", None),
    # ---- Phase 6: scheduler, morsel scan, parallel executor, partitioned merges, sort, CSV ---------
    ("scheduler: participants are not given distinct ids",
     "src/execution/task_scheduler.cpp",
     "const size_t id = job->joined++;", "const size_t id = job->joined;", None),
    ("scheduler: a fully staffed job stays in the queue, so more workers join than allowed",
     "src/execution/task_scheduler.cpp",
     "if (job->joined >= job->max_participants) {", "if (false) {", None),
    ("scheduler: the caller returns while a worker is still inside the body",
     "src/execution/task_scheduler.cpp",
     "job.done.wait(lock, [&job] { return job.running == 0; });",
     "job.done.wait(lock, [&job] { return true; });", None),
    ("scheduler: a worker's exception is lost",
     "src/execution/task_scheduler.cpp",
     "if (error && !job->error) {", "if (false) {", None),
    ("scheduler: ParallelFor keeps handing out indexes after a failure",
     "src/execution/task_scheduler.cpp",
     "failed.store(true, std::memory_order_relaxed);", ";", None),
    ("scheduler: ParallelFor skips every second index",
     "src/execution/task_scheduler.cpp",
     "next.fetch_add(1, std::memory_order_relaxed)", "next.fetch_add(2, std::memory_order_relaxed)", None),
    ("morsels: claiming skips every other morsel",
     "src/storage/table.cpp",
     "next_.fetch_add(1, std::memory_order_relaxed)", "next_.fetch_add(2, std::memory_order_relaxed)", None),
    ("morsels: the last morsel of a row group is not clipped to the group",
     "src/storage/table.cpp",
     "m.count = std::min(morsel_rows, group.count() - offset);", "m.count = morsel_rows;", None),
    ("morsels: a row group whose size is a multiple of the morsel size gets an extra empty morsel",
     "src/storage/table.cpp",
     "offset < group.count(); offset += morsel_rows", "offset <= group.count(); offset += morsel_rows", None),
    ("morsels: ReadVector ignores the morsel's offset inside its row group",
     "src/storage/table.cpp",
     "Scan(morsel.offset + first, n, out.column(i))", "Scan(first, n, out.column(i))", None),
    ("morsels: groups skipped by their zone map are not counted",
     "src/storage/table.cpp",
     "skipped_++;\n            continue;\n        }\n        scanned_++;\n        kept.push_back(",
     "continue;\n        }\n        scanned_++;\n        kept.push_back(", None),
    ("executor: the number of participants ignores the source's MaxSourceThreads",
     "src/execution/pipeline.cpp",
     "p.source->MaxSourceThreads(*global_source)", "scheduler_->threads()", None),
    ("executor: a pipeline with ONE parallel operator among serial ones runs in parallel",
     "src/execution/pipeline.cpp",
     "return std::all_of(p.operators.begin(), p.operators.end(),",
     "return std::any_of(p.operators.begin(), p.operators.end(),", None),
    ("executor: a sink that is not parallel does not keep the pipeline on one thread",
     "src/execution/pipeline.cpp",
     "if (!p.source->ParallelSource() || !p.sink->ParallelSink()) {",
     "if (!p.source->ParallelSource()) {", None),
    ("executor: the batch index is not passed from the source to the sink",
     "src/execution/pipeline.cpp",
     "local_sink->batch_index = local_source->batch_index;", ";", None),
    ("executor: a thread's local sink state is never combined",
     "src/execution/pipeline.cpp",
     "p.sink->Combine(global_sink, *local_sink);", ";", None),
    ("collector: chunks come back in reverse batch order",
     "src/execution/basic_operators.cpp",
     "return a.first < b.first;", "return a.first > b.first;", None),
    ("collector: chunks of one batch are sorted unstably",
     "src/execution/basic_operators.cpp",
     "std::stable_sort(chunks.begin(), chunks.end(),", "std::sort(chunks.begin(), chunks.end(),", None),
    ("insert: rows are staged in arrival order instead of batch order",
     "src/execution/basic_operators.cpp",
     "SortByBatch(g.chunks);", ";", None),
    ("scan: morsel chunks carry no batch index",
     "src/execution/basic_operators.cpp",
     "l.batch_index = l.morsel.index;", ";", None),
    ("scan: the adaptive morsel size ignores the thread count",
     "src/storage/table.cpp",
     "AlignUp(kept_rows / (threads * kMorselsPerThread), kVectorSize)",
     "AlignUp(kept_rows / kMorselsPerThread, kVectorSize)", None),
    ("scan: the adaptive morsel size may exceed the built-in size",
     "src/storage/table.cpp",
     "morsel_rows = std::clamp<idx_t>(even, kVectorSize, morsel_rows);",
     "morsel_rows = std::max<idx_t>(even, kVectorSize);", None),
    ("scan: an explicitly set default morsel size is adapted anyway",
     "src/storage/table.cpp",
     "morsel_rows == 0 && threads > 1 && MorselRowsSetting().load(std::memory_order_relaxed) == 0;",
     "morsel_rows == 0 && threads > 1;", None),
    ("scan: the adaptive morsel size counts rows of pruned groups too",
     "src/storage/table.cpp",
     "kept_rows += group.count();", "kept_rows += group.count() * 4;", None),
    ("scan: the thread hint never reaches the morsel scan",
     "src/execution/basic_operators.cpp",
     "std::make_unique<ScanGlobalState>(snapshot_, column_ids_, filters_, threads_)",
     "std::make_unique<ScanGlobalState>(snapshot_, column_ids_, filters_, 1)", None),
    ("executor: a serial pipeline's source is told the whole pool will read it",
     "src/execution/pipeline.cpp",
     "p.source->SetThreadHint(parallel ? scheduler_->threads() : 1);",
     "p.source->SetThreadHint(scheduler_ != nullptr ? scheduler_->threads() : 1);", None),
    ("aggregate: merging whole tables also merges table 0 into itself",
     "src/execution/hash_aggregate.cpp",
     "for (size_t i = 1; i < locals.size(); i++) {", "for (size_t i = 0; i < locals.size(); i++) {", None),
    ("group table: CombineGroups ignores its position in the group list after the first vector",
     "src/execution/group_table.cpp",
     "Gather(c, groups + at, m, keys.column(c))", "Gather(c, groups, m, keys.column(c))", None),
    ("aggregate state: the SUM range check rejects the largest BIGINT",
     "src/execution/aggregate_state.cpp",
     "sum > std::numeric_limits<int64_t>::max()", "sum >= std::numeric_limits<int64_t>::max()", None),
    ("aggregate state: the SUM range check rejects the smallest BIGINT",
     "src/execution/aggregate_state.cpp",
     "sum < std::numeric_limits<int64_t>::min()", "sum <= std::numeric_limits<int64_t>::min()", None),
    ("aggregate state: AVG's subset merge drops the counts",
     "src/execution/aggregate_state.cpp",
     "sums_[to[i]].Add(s.sums_[from[i]]);\n            counts_[to[i]] += s.counts_[from[i]];",
     "sums_[to[i]].Add(s.sums_[from[i]]);\n            ;", None),
    ("aggregate state: MIN/MAX subset merge offers the destination's own value",
     "src/execution/aggregate_state.cpp",
     "Offer(to[i], static_cast<T>(s.values_[from[i]]));", "Offer(to[i], static_cast<T>(s.values_[to[i]]));", None),
    ("aggregate state: string MIN/MAX subset merge offers the destination's own value",
     "src/execution/aggregate_state.cpp",
     "Offer(to[i], s.values_[from[i]]);", "Offer(to[i], s.values_[to[i]]);", None),
    ("join build: each thread's partial last chunk is not copied into the build side",
     "src/execution/hash_join.cpp",
     "g.payload.AppendStore(part.payload);", ";", None),
    ("join build: the key chunks are not adopted (keys and payload fall out of step)",
     "src/execution/hash_join.cpp",
     "g.keys.AdoptFullChunks(part.keys);", ";", None),
    ("join build: bucket partitions use the whole bucket number",
     "src/execution/hash_join.cpp",
     "const unsigned shift = bucket_bits > partition_bits ? bucket_bits - partition_bits : 0;",
     "const unsigned shift = 0;", None),
    ("join build: the scatter offsets of different ranges overlap",
     "src/execution/hash_join.cpp",
     "running += count;", "running += 0 * count;", None),
    ("join build: chains list rows in reverse build order",
     "src/execution/hash_join.cpp",
     "for (uint32_t i = partition_start[p + 1]; i-- > partition_start[p];) {",
     "for (uint32_t i = partition_start[p]; i < partition_start[p + 1]; i++) {", None),
    ("sort: the merge gives ties to the right-hand run",
     "src/execution/sort.cpp",
     "!less(order_[s.b + j - 1], order_[s.a + i])", "less(order_[s.b + j - 1], order_[s.a + i])", None),
    ("sort: runs are sorted unstably",
     "src/execution/sort.cpp",
     "std::stable_sort(order_.begin() + static_cast<long>(bounds[r]),",
     "std::sort(order_.begin() + static_cast<long>(bounds[r]),", None),
    ("sort: an odd run out is dropped from the merge round",
     "src/execution/sort.cpp",
     "if (run_count % 2 == 1) { // an odd run out is carried over unchanged", "if (false) {", None),
    ("sort: the sorted source ignores where the output range starts (OFFSET)",
     "src/execution/sort.cpp",
     "const idx_t first = s.first + chunk * kVectorSize;", "const idx_t first = chunk * kVectorSize;", None),
    ("sort: sorted chunks carry no batch index",
     "src/execution/sort.cpp",
     "local.batch_index = chunk;", "(void)local;", None),
    ("csv: an open quote is never closed by the scanner",
     "src/io/csv_reader.cpp",
     "state_ = c == '\"' ? State::QuoteSeen : State::InQuotes;", "state_ = State::InQuotes;", None),
    ("csv: a doubled quote inside a quoted field closes it",
     "src/io/csv_reader.cpp",
     "case State::QuoteSeen: // `\"\"` is an escaped quote; anything else closed the field\n            state_ = c == '\"' ? State::InQuotes :",
     "case State::QuoteSeen: // `\"\"` is an escaped quote; anything else closed the field\n            state_ = c == '\"' ? State::Unquoted :", None),
    ("csv: record starts of the quote-free index are off by one",
     "src/io/csv_reader.cpp",
     "lines[k] = {static_cast<uint64_t>(previous + 1),", "lines[k] = {static_cast<uint64_t>(previous + 2),", None),
    ("csv: blank lines stay records in the quote-free index",
     "src/io/csv_reader.cpp",
     "return IsBlank(data + r.begin, r.length);", "return (void)r, false;", None),
    ("csv: the header record is parsed as data by the parallel loader",
     "src/io/csv_reader.cpp",
     "records.erase(records.begin());", ";", None),
    ("csv: the parallel loader does not enforce NOT NULL",
     "src/io/csv_reader.cpp",
     "staging->ValidateChunk(chunk);", ";", None),
    ("csv: a failing row group never records itself as failed",
     "src/io/csv_reader.cpp",
     "while (g < seen && !first_failed.compare_exchange_weak(seen, g)) {",
     "while (g > seen && !first_failed.compare_exchange_weak(seen, g)) {", None),
    ("table: AppendRowGroups discards the open tail instead of sealing it",
     "src/storage/table.cpp",
     "sealed_.push_back(open_->Seal()); // so the new groups follow it in order",
     "(void)open_->Seal(); // so the new groups follow it in order", None),
    ("database: SetThreads(0) means one thread, not one per hardware thread",
     "src/main/database.cpp",
     "threads = TaskScheduler::HardwareThreads();\n    }\n    threads = std::min",
     "threads = 1;\n    }\n    threads = std::min", None),
    ('commit: an INSERT is acknowledged before its log record is fsynced',
     'src/main/storage_manager.cpp',
     'LogAppend(*target, *staging);\n            if (options_.sync == SyncMode::Full) {\n                wal_->Sync();\n            }',
     'LogAppend(*target, *staging);', None),
    ('commit: CREATE TABLE is acknowledged before its log record is fsynced',
     'src/main/storage_manager.cpp',
     'WriteTableDefinition(w, *table);\n        const uint64_t before = wal_->size();\n        try {\n            wal_->AppendFrame(w.buffer(), true);\n            if (options_.sync == SyncMode::Full) {\n                wal_->Sync();\n            }',
     'WriteTableDefinition(w, *table);\n        const uint64_t before = wal_->size();\n        try {\n            wal_->AppendFrame(w.buffer(), true);', None),
    ('commit: DROP TABLE is acknowledged before its log record is fsynced',
     'src/main/storage_manager.cpp',
     'w.String(name);\n        const uint64_t before = wal_->size();\n        try {\n            wal_->AppendFrame(w.buffer(), true);\n            if (options_.sync == SyncMode::Full) {\n                wal_->Sync();\n            }',
     'w.String(name);\n        const uint64_t before = wal_->size();\n        try {\n            wal_->AppendFrame(w.buffer(), true);', None),
    ('commit: the stale-table check before an INSERT is removed',
     'src/main/storage_manager.cpp',
     'if (catalog_.TryGetTable(target->name()) != target) {',
     'if (false) {', None),
    ('commit: the non-final frames of a multi-frame statement are marked committed',
     'src/main/storage_manager.cpp',
     'wal_->AppendFrame(w.buffer(), false);',
     'wal_->AppendFrame(w.buffer(), true);', None),
    ('commit: the last frame of a statement is not marked committed',
     'src/main/storage_manager.cpp',
     'wal_->AppendFrame(w.buffer(), true); // the commit frame',
     'wal_->AppendFrame(w.buffer(), false); // the commit frame', None),
    ('commit: a failed log write does not make the database read-only',
     'src/main/storage_manager.cpp',
     '} catch (...) {\n            failed_ = true;\n            throw;\n        }\n        transactions_total_++;\n        bytes_uncheckpointed_ += wal_->size() - before;\n        try {',
     '} catch (...) {\n            throw;\n        }\n        transactions_total_++;\n        bytes_uncheckpointed_ += wal_->size() - before;\n        try {', None),
    ('checkpoint: the old log is not fsynced before the new log starts',
     'src/main/storage_manager.cpp',
     'wal_->Sync();\n            auto fresh = WalWriter::Create',
     'auto fresh = WalWriter::Create', None),
    ('checkpoint: the directory is not fsynced after the new log is created',
     'src/main/storage_manager.cpp',
     'new_epoch);\n            fs_->SyncDirectory(dir_);\n            wal_ = std::move(fresh);',
     'new_epoch);\n            wal_ = std::move(fresh);', None),
    ('checkpoint: obsolete files are removed before the new checkpoint is in place',
     'src/main/storage_manager.cpp',
     'fs_->Rename(tmp_path, final_path);',
     'RemoveObsoleteFiles(new_epoch, false);\n    fs_->Rename(tmp_path, final_path);', None),
    ('checkpoint: the file is not fsynced before it is renamed into place',
     'src/storage/checkpoint.cpp',
     'put(tr.buffer());\n    file->Sync();',
     'put(tr.buffer());', None),
    ('checkpoint: a checkpoint is written even when nothing was committed since the last',
     'src/main/storage_manager.cpp',
     'if (transactions_total_ == transactions_checkpointed_) {',
     'if (false) {', None),
    ('close: the database does not checkpoint when it is closed',
     'src/main/storage_manager.cpp',
     'if (options_.checkpoint_on_close) {',
     'if (false) {', None),
    ('recovery: stale files are not removed',
     'src/main/storage_manager.cpp',
     'transactions_total_ = recovery_.transactions;\n    RemoveObsoleteFiles(base, true);',
     'transactions_total_ = recovery_.transactions;', None),
    ('recovery: an older log with a damaged tail is accepted',
     'src/main/storage_manager.cpp',
     'if (!newest && (!scan.header_valid || scan.discarded_bytes() != 0)) {',
     'if (false) {', None),
    ('recovery: a missing log after the checkpoint is ignored',
     'src/main/storage_manager.cpp',
     'if (chain.empty() || chain.front() != base) {',
     'if (false) {', None),
    ('recovery: a gap in the chain of logs is ignored',
     'src/main/storage_manager.cpp',
     'if (chain[i] != base + i) {',
     'if (false) {', None),
    ('recovery: a torn log tail is not cut off before appending',
     'src/storage/wal.cpp',
     'if (file->Size() != valid_size) {',
     'if (false) {', None),
    ('wal: the replay goes past the last committed transaction',
     'src/storage/wal.cpp',
     'while (pos < scan.valid_size) {',
     'while (pos + kWalFrameHeaderSize <= scan.file_size) {', None),
    ('wal: sequence numbers are not checked',
     'src/storage/wal.cpp',
     'h.sequence != sequence ||',
     'false ||', None),
    ('wal: every frame counts as a commit',
     'src/storage/wal.cpp',
     'if ((h.flags & kWalCommitFlag) != 0) {',
     'if (true) {', None),
    ("wal: a frame's checksum is not verified by the scan",
     'src/storage/wal.cpp',
     'if (FrameCrc(h.length, h.sequence, h.flags, payload.data()) != h.crc) {\n            break;',
     'if (false) {\n            break;', None),
    ('wal: a failed write does not poison the writer',
     'src/storage/wal.cpp',
     'poisoned_ = true; // a prefix of the frame may be on disk',
     '// a prefix of the frame may be on disk', None),
    ('wal: Sync() does not fsync',
     'src/storage/wal.cpp',
     'try {\n        file_->Sync();\n    } catch (...) {',
     'try {\n        ;\n    } catch (...) {', None),
    ('checkpoint reader: block checksums are not verified',
     'src/storage/checkpoint.cpp',
     'if (Crc32c(block.data(), block.size() - 4) != stored) {',
     'if (false) {', None),
    ('checkpoint reader: bytes after the trailer are accepted',
     'src/storage/checkpoint.cpp',
     'footer_offset + footer_size + kTrailerSize != size) {',
     'footer_offset + footer_size + kTrailerSize > size) {', None),
    # (the directory's check for a group of zero rows is equivalent to ReadSegment's: a group has at
    # least one column, and a segment of zero rows is rejected there, so no input tells them apart)
    ('checkpoint reader: a row group larger than the table\'s is accepted',
     'src/storage/checkpoint.cpp',
     'if (g.rows == 0 || g.rows > group_size) {',
     'if (g.rows == 0) {', None),
    ('checkpoint reader: a segment may extend past the data area',
     'src/storage/checkpoint.cpp',
     's.offset + s.size > footer_offset) {',
     'false) {', None),
    ("segment io: the statistics' NULL count is not checked against the validity bits (encoded)",
     'src/storage/segment_io.cpp',
     'const idx_t nulls = ReadValidity(r, count, validity);\n        if (nulls != stats.null_count) {',
     'const idx_t nulls = ReadValidity(r, count, validity);\n        if (false) {', None),
    ('segment io: the values of NULL rows are written too',
     'src/storage/segment_io.cpp',
     'if (!validity.IsValid(row)) {\n                continue;\n            }',
     'if (false) {\n                continue;\n            }', None),
    ('chunk io: an oversized row count is accepted',
     'src/storage/segment_io.cpp',
     'if (n > kVectorSize) {',
     'if (false) {', None),
    ('encoding: run ends need not increase',
     'src/storage/encoding.cpp',
     'if (e <= previous || e > count) {',
     'if (e > count) {', 'asan'),
    ('encoding: a dictionary code may exceed the dictionary',
     'src/storage/encoding.cpp',
     'if (codes[i] >= dictionary_size) {',
     'if (false) {', None),
    ('encoding: packed vectors may lie outside their payload',
     'src/storage/encoding.cpp',
     'if (width > 0 && (offset > payload_size || PackedBytes(rows, width) > payload_size - offset)) {',
     'if ((void)offset, (void)rows, (void)payload_size, false) {', 'asan'),
    ('table: LoadRowGroups seals a short last group instead of re-opening it',
     'src/storage/table.cpp',
     'if (!groups.empty() && groups.back()->count() < row_group_size_) {',
     'if (false) {', None),
    ('catalog: AddTable accepts a name that exists',
     'src/catalog/catalog.cpp',
     'if (!tables_.emplace(key, table).second) {',
     'if (false) {', None),
    ('database: an INSERT into a dropped table is accepted without storage',
     'src/main/database.cpp',
     'if (catalog_.TryGetTable(target->name()) != target) {',
     'if (false) {', None),
    ('connection: CHECKPOINT does nothing',
     'src/main/connection.cpp',
     'db_.Checkpoint();\n        return QueryResult::Empty();',
     'return QueryResult::Empty();', None),
    ('memory fs: fsync does not make data durable',
     'src/io/memory_file_system.cpp',
     'inode_->durable = inode_->data;',
     ';', None),
    ("memory fs: a directory fsync does not persist a rename's new name",
     'src/io/memory_file_system.cpp',
     'durable_.erase(op.a);\n            durable_[op.b] = op.inode;',
     'durable_.erase(op.a);', None),
    ('memory fs: a crash that keeps everything loses unsynced data',
     'src/io/memory_file_system.cpp',
     'bytes = inode->data;\n            break;',
     'break;', None),
    ('memory fs: a prefix crash keeps every unsynced write',
     'src/io/memory_file_system.cpp',
     'const size_t kept = rng.UpTo(ops.size());',
     'const size_t kept = ops.size();', None),

    # ---- Phase 8: subqueries and WITH --------------------------------------------------------
    ('subquery: a correlated count() of no rows is NULL instead of 0 (the count bug)',
     'src/planner/bind_subquery.cpp',
     'if (p.empty_default != nullptr) {',
     'if (p.empty_default != nullptr && false) {', None),
    ('subquery: a correlated scalar subquery joins INNER and drops rows without a group',
     'src/planner/bind_subquery.cpp',
     'join->join_type = JoinType::Left;',
     'join->join_type = JoinType::Inner;', None),
    ('subquery: NOT IN is a plain anti join (NULLs on the right are ignored)',
     'src/planner/bind_subquery.cpp',
     'join->join_type = negated ? JoinType::AntiNullAware : JoinType::Semi;',
     'join->join_type = negated ? JoinType::Anti : JoinType::Semi;', None),
    ('subquery: an uncorrelated scalar subquery is never guarded against several rows',
     'src/planner/bind_subquery.cpp',
     'if (IsSingleRow(*plan)) {',
     'if (IsSingleRow(*plan) || true) {', None),
    ('scalar guard: a second row is tolerated',
     'src/execution/scalar_guard.cpp',
     'if (g.rows + input.size() > 1) {',
     'if (g.rows + input.size() > 2) {', None),
    ('scalar guard: no row yields a value instead of NULL',
     'src/execution/scalar_guard.cpp',
     'g.sink->rows == 1 ? g.sink->row.GetValue(c, 0) : Value::Null(types()[c])',
     'g.sink->rows <= 1 ? g.sink->row.GetValue(c, 0) : Value::Null(types()[c])', None),
    ('null-aware anti join: a NULL on the build side does not empty the result',
     'src/execution/hash_join.cpp',
     'const bool none = !all && build.rows_with_null_key > 0;',
     'const bool none = false && !all && build.rows_with_null_key > 0;', None),
    ('null-aware anti join: an empty build side is not recognised (NULL probe keys are dropped)',
     'src/execution/hash_join.cpp',
     'const bool all = build.rows_seen == 0;',
     'const bool all = false && build.rows_seen == 0;', None),
    ('null-aware anti join: a NULL probe key is kept',
     'src/execution/hash_join.cpp',
     'if (all || (st.key_ok[i] != 0 && st.matched[i] == 0)) {',
     'if (all || st.matched[i] == 0) {', None),
    ('hash join: an uncorrelated EXISTS is true although the subquery has no rows',
     'src/execution/hash_join.cpp',
     'std::fill(st.matched.begin(), st.matched.end(), build.payload.Count() > 0 ? 1 : 0);',
     'std::fill(st.matched.begin(), st.matched.end(), 1);', None),
    ('planner: an anti join is planned as a semi join',
     'src/execution/physical_planner.cpp',
     'case JoinType::Anti:\n            type = PhysicalJoinType::Anti;',
     'case JoinType::Anti:\n            type = PhysicalJoinType::Semi;', None),
    ('optimizer: a filter under a semi / anti join is not lifted past it (the join cannot sink)',
     'src/planner/optimizer.cpp',
     'if (join.children[0]->kind == LogicalKind::Filter) {',
     'if (false && join.children[0]->kind == LogicalKind::Filter) {', None),
    ('optimizer: a semi / anti join that removes almost nothing still sinks to the leaf',
     'src/planner/optimizer.cpp',
     'if ((in_a || in_b) && !HasOneRowInput(inner) && ShrinksItsInput(join)) {',
     'if ((in_a || in_b) && !HasOneRowInput(inner) && (ShrinksItsInput(join) || true)) {', None),
    ('optimizer: a semi / anti join sinks below the join with a scalar subquery (a probe per row it discards)',
     'src/planner/optimizer.cpp',
     'if ((in_a || in_b) && !HasOneRowInput(inner) && ShrinksItsInput(join)) {',
     'if ((in_a || in_b) && (HasOneRowInput(inner) || true) && ShrinksItsInput(join)) {', None),
    ('optimizer: a join counts as one-row from three rows up (its left input)',
     'src/planner/optimizer.cpp',
     'return estimator.Of(*join.children[0]).rows <= 1.5 ||',
     'return estimator.Of(*join.children[0]).rows <= 3.5 ||', None),
    ('optimizer: a join counts as one-row from three rows up (its right input)',
     'src/planner/optimizer.cpp',
     'estimator.Of(*join.children[1]).rows <= 1.5;',
     'estimator.Of(*join.children[1]).rows <= 3.5;', None),
    ('optimizer: only the left input of a join can be its one row',
     'src/planner/optimizer.cpp',
     'estimator.Of(*join.children[1]).rows <= 1.5;',
     'false;', None),
    ('optimizer: only the right input of a join can be its one row',
     'src/planner/optimizer.cpp',
     'return estimator.Of(*join.children[0]).rows <= 1.5 ||',
     'return false ||', None),
    ('optimizer: a semi join pushed into the left input of an inner join keeps the old subquery columns',
     'src/planner/optimizer.cpp',
     'return o < lw ? o : o - b_width;',
     'return o;', None),
    ('optimizer: a semi join pushed into the right input of an inner join does not shift its columns',
     'src/planner/optimizer.cpp',
     'RemapColumns(*join.condition, [a_width](idx_t o) { return o - a_width; });',
     'RemapColumns(*join.condition, [a_width](idx_t o) { return o + 0 * a_width; });', None),
    ('optimizer: a semi join is pushed below any join, outer joins included',
     'src/planner/optimizer.cpp',
     'if (inner.join_type == JoinType::Inner || inner.join_type == JoinType::Cross) {',
     'if (true) {', None),
    ('cte: duplicate names in one WITH are accepted',
     'src/planner/binder.cpp',
     'if (Lower(select.ctes[k].name) == name) {',
     'if (false && Lower(select.ctes[k].name) == name) {', None),
    ('cte: a WITH query does not shadow a table of the same name',
     'src/planner/binder.cpp',
     'if (const CteEntry* cte = FindCte(Lower(ref.name))) {',
     'if (const CteEntry* cte = FindCte(Lower(ref.name)); cte && false) {', None),
    ('cte: a WITH query cannot see the ones defined before it',
     'src/planner/binder.cpp',
     'binder_.cte_storage_.push_back({name, &select.ctes[i], binder_.cte_head_});',
     'binder_.cte_storage_.push_back({name, &select.ctes[i], nullptr});', None),

    # ---- Phase 8: statistics, estimates, join order -------------------------------------------
    ('hyperloglog: merging takes the smaller register',
     'src/storage/hyperloglog.cpp',
     'registers_[i] = std::max(registers_[i], other.registers_[i]);',
     'registers_[i] = std::min(registers_[i], other.registers_[i]);', None),
    ('hyperloglog: linear counting is never used for small counts',
     'src/storage/hyperloglog.cpp',
     'if (linear <= kLinearCountingLimit * m) {',
     'if (false && linear <= kLinearCountingLimit * m) {', None),
    ('hyperloglog: a register holds one less than the position of the first set bit',
     'src/storage/hyperloglog.h',
     'static_cast<uint8_t>(__builtin_clzll(rest) + 1);',
     'static_cast<uint8_t>(__builtin_clzll(rest));', None),
    ('table statistics: the NULL counts of the segments are not summed',
     'src/storage/table_statistics.cpp',
     'out.null_count += st.null_count;',
     'out.null_count = st.null_count;', None),
    ('table statistics: a segment without bounds keeps the bounds of the others',
     'src/storage/table_statistics.cpp',
     'if (bounds_lost) {',
     'if (false && bounds_lost) {', None),
    ('table statistics: the distinct estimate may exceed the number of values',
     'src/storage/table_statistics.cpp',
     'out.distinct = std::min(merged.Estimate(), non_null);',
     'out.distinct = merged.Estimate();', None),
    ('table: cached statistics are served after the table changed',
     'src/storage/table.cpp',
     'if (stats_cache_ != nullptr && stats_version_ == version) {',
     'if (stats_cache_ != nullptr) {', None),
    ('table: a small load seals the open row group as a short one',
     'src/storage/table.cpp',
     'if (ours_partial && staging->sealed_.empty()) {',
     'if (false && ours_partial && staging->sealed_.empty()) {', None),
    ('sketch io: a sketch is always stored in the dense form',
     'src/storage/segment_io.cpp',
     'if (used * 3 + 2 < HyperLogLog::kRegisters) {',
     'if (false && used * 3 + 2 < HyperLogLog::kRegisters) {', None),
    ('sketch io: the registers of a sparse sketch need not increase',
     'src/storage/segment_io.cpp',
     'static_cast<long>(index) <= previous ||',
     '(static_cast<long>(index) <= previous && false) ||', None),
    ('sketch io: a sketch may disagree with the NULL count of its segment',
     'src/storage/segment_io.cpp',
     'stats.distinct->Empty() != stats.AllNull()',
     'false', None),
    ('estimates: an equality with a constant outside the bounds is not empty',
     'src/planner/cardinality.cpp',
     '(lo < 0 || hi > 0)) {',
     'false) {', None),
    ('estimates: a range counts the value at its end twice',
     'src/planner/cardinality.cpp',
     'at_most = Clamp01((std::floor(position) + 1) / points);',
     'at_most = Clamp01((std::floor(position) + 2) / points);', None),
    ('estimates: a dense integer range with a noisy distinct count is not snapped to its size',
     'src/planner/cardinality.cpp',
     'if (whole && points >= 0.9 * (*hi - *lo + 1)) {',
     'if (whole && points >= 1e18 * (*hi - *lo + 1)) {', None),
    ('estimates: a lower and an upper bound on one column are independent shares',
     'src/planner/cardinality.cpp',
     'upper->column != lower->column) {',
     'upper->column != lower->column || true) {', None),
    ('estimates: OR adds the probabilities of its sides',
     'src/planner/cardinality.cpp',
     'return Clamp01(a + b - a * b);',
     'return Clamp01(a + b);', None),
    ('estimates: a composite join key is not capped by the larger input',
     'src/planner/cardinality.cpp',
     'combinations = std::min(combinations, std::max({1.0, left.rows, right.rows}));',
     'combinations = combinations * 1.0;', None),
    ('estimates: a left join may return fewer rows than its left input',
     'src/planner/cardinality.cpp',
     'rows = std::max(inner_rows, left.rows);',
     'rows = inner_rows;', None),
    ('estimates: an anti join keeps what the semi join keeps',
     'src/planner/cardinality.cpp',
     '(type == JoinType::Semi ? match : 1.0 - match)',
     '(type == JoinType::Semi ? match : match)', None),
    ('estimates: a filter does not cap the distinct counts at the rows left',
     'src/planner/cardinality.cpp',
     'c.distinct = std::max(1.0, std::min(c.distinct, room));\n    }\n    return out;\n}\n\nnamespace {\n\nstruct KeyPair',
     'c.distinct = std::max(1.0, std::min(c.distinct, room * 1e18));\n    }\n    return out;\n}\n\nnamespace {\n\nstruct KeyPair', None),
    ('join order: a cross product may join two sets that a predicate could have joined',
     'src/planner/join_order.cpp',
     'if (connected[part] >= 0 && connected[other] >= 0 && Connected(edges, part, other)) {',
     'if (connected[part] >= 0 && connected[other] >= 0 && (Connected(edges, part, other) || true)) {', None),
    ('join order: the smaller input probes',
     'src/planner/join_order.cpp',
     'const bool x_probes = tie ? nx.set < ny.set : nx.rows > ny.rows;',
     'const bool x_probes = tie ? nx.set < ny.set : nx.rows < ny.rows;', None),
    ('join order: the rows built into the hash table are counted once',
     'src/planner/join_order.cpp',
     'return out_rows + 2.0 * build + probe;',
     'return out_rows + build + probe;', None),
    ('join order: equalities between the same two relations are not a composite key',
     'src/planner/join_order.cpp',
     'const double combinations = std::min(key.combinations, std::max(1.0, larger));',
     'const double combinations = std::max(key.combinations, std::max(1.0, larger));', None),
    ('optimizer: a conjunct that is always TRUE stays in the plan',
     'src/planner/optimizer.cpp',
     'part->value->GetBoolean()) {\n            continue;',
     'part->value->GetBoolean() && false) {\n            continue;', None),
    ('optimizer: a predicate that mentions no relation is never placed on the join tree',
     'src/planner/optimizer.cpp',
     'can_mask ? (mask[c] == 0 ? last',
     'can_mask ? (mask[c] == 0 ? false', None),

    ('estimates: the years of a date column are one per date',
     'src/planner/cardinality.cpp',
     'return bounded(std::floor((*hi - *lo) / 365.2425) + 2);',
     'return argument(0);', None),
    ('estimates: an integer expression may take more values than its range holds',
     'src/planner/cardinality.cpp',
     'product = std::min(product, std::floor(range->second - range->first) + 1);',
     'product = product + 0 * range->second;', None),
    ('estimates: a CASE of constants may take as many values as it has rows',
     'src/planner/cardinality.cpp',
     'return static_cast<double>(constants.size());',
     'return rows;', None),
    ('estimates: a comparison may take as many values as it has rows',
     'src/planner/cardinality.cpp',
     'return 3; // TRUE, FALSE, NULL',
     'return rows; // TRUE, FALSE, NULL', None),

    ('hash join: a build with fewer buckets than partitions shifts by a negative amount (UBSan only)',
     'src/execution/hash_join.cpp',
     'const unsigned shift = bucket_bits > partition_bits ? bucket_bits - partition_bits : 0;',
     'const unsigned shift = bucket_bits - partition_bits;', 'asan'),
    ('estimates: a semi / anti join measures the left keys against the distinct values the rows left hold',
     'src/planner/cardinality.cpp',
     'Clamp01(r.distinct / std::max(1.0, l.Domain()))',
     'Clamp01(r.distinct / std::max(1.0, l.distinct))', None),
    ('estimates: a scan reports no domain for its columns',
     'src/planner/cardinality.cpp',
     'c.domain = c.distinct;\n            c.null_fraction = stats->NullFraction(column);',
     'c.null_fraction = stats->NullFraction(column);', None),

    # ---- Phase 8: deterministic floating-point sums --------------------------------------------
    ('compensated sum: a grouped DOUBLE sum adds plain doubles (order-dependent)',
     'src/execution/aggregate_state.cpp',
     'sums_[groups[i]].Add(data[u.sel[i]]);\n                has_[groups[i]] = 1;',
     'sums_[groups[i]].hi += data[u.sel[i]];\n                has_[groups[i]] = 1;', None),
    ('compensated sum: the rounding error of an addition is not collected',
     'src/common/compensated_sum.h',
     'lo += (hi - (s - bb)) + (x - bb);',
     'lo += (hi - (s - bb));', None),
    ('compensated sum: merging two sums forgets the low part of the second',
     'src/common/compensated_sum.h',
     'lo += (hi - (s - bb)) + (other.hi - bb) + other.lo;',
     'lo += (hi - (s - bb)) + (other.hi - bb);', None),
    ('compensated sum: the SIMD lanes are merged without their low parts',
     'src/kernels/aggregate.cpp',
     'sum.Add(CompensatedSum{his[lane], los[lane]});',
     'sum.Add(his[lane]);', None),
    ('compensated sum: AVG divides the high part only',
     'src/execution/aggregate_state.cpp',
     'o[i] = sums_[first + i].Value() / static_cast<double>(counts_[first + i]);',
     'o[i] = sums_[first + i].hi / static_cast<double>(counts_[first + i]);', None),

    # ---- Phase 8: EXPLAIN ANALYZE ---------------------------------------------------------------
    ('explain analyze: the rows of streaming operators are not counted',
     'src/execution/pipeline.cpp',
     'profile->rows_out.fetch_add(output.size(), std::memory_order_relaxed);',
     '', None),
    ('explain analyze: the rows a sink consumed are not counted',
     'src/execution/pipeline.cpp',
     'sink_profile->rows_in.fetch_add(input.size(), std::memory_order_relaxed);',
     '', None),
    ('explain analyze: the rows of a source are not counted',
     'src/execution/pipeline.cpp',
     'source_profile->rows_out.fetch_add(chunk.size(), std::memory_order_relaxed);',
     '', None),
    ('explain analyze: the ORDER BY under a LIMIT is not tied to the top-N that ran it',
     'src/execution/physical_planner.cpp',
     'plan_.origins.push_back({&child, &top_n});',
     '', None),
]


def pattern_for(text):
    """Regex matching `text` with every whitespace run treated as flexible, so mutation anchors
    survive clang-format reflowing the code."""
    return re.compile(r"\s+".join(re.escape(tok) for tok in text.split()))


BACKUP_DIR = ROOT / "build" / "mutation_backup"


# The slowest legitimate test takes about a minute under TSan; a mutant that hangs or crawls
# should be reported, not waited for.
TEST_TIMEOUT_SECONDS = 600


def run(cmd):
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, errors="replace")


def pattern_for(text):
    """Regex matching `text` with every whitespace run treated as flexible, so mutation anchors
    survive clang-format reflowing the code."""
    return re.compile(r"\s+".join(re.escape(tok) for tok in text.split()))


def recover_leftovers():
    """Restore originals left in the backup dir by a run that died mid-mutation."""
    if not BACKUP_DIR.exists():
        return
    for backup in sorted(BACKUP_DIR.rglob("*")):
        if backup.is_file():
            rel = backup.relative_to(BACKUP_DIR)
            (ROOT / rel).write_text(backup.read_text())
            backup.unlink()
            print(f"RECOVERED  restored {rel} from an interrupted mutation run")


def targets():
    return sorted({rel for _, rel, *_ in MUTATIONS})


def dirty_targets():
    return [f for f in targets() if run(["git", "diff", "--quiet", "--", f]).returncode != 0]


def _terminate(signum, _frame):
    raise SystemExit(128 + signum)  # unwinds through `finally`, which restores the file


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preset", default="debug")
    ap.add_argument("--only", default="")
    ap.add_argument("--check", action="store_true",
                    help="only validate that every anchor matches exactly once; build nothing")
    ap.add_argument("--allow-dirty", action="store_true",
                    help="run even if mutation target files have uncommitted changes")
    args = ap.parse_args()

    for sig in (signal.SIGTERM, signal.SIGHUP, signal.SIGINT):
        signal.signal(sig, _terminate)

    recover_leftovers()
    dirty = dirty_targets()
    if dirty and not args.allow_dirty:
        print("REFUSING to run: these mutation targets have uncommitted changes, so a restored "
              "file could not be told apart from a mutated one:\n  " + "\n  ".join(dirty) +
              "\nCommit or stash them (or pass --allow-dirty).")
        return 2
    snapshot = {f: (ROOT / f).read_text() for f in targets()}

    wanted = [w for w in args.only.split("|") if w]  # `--only "parser:|lexer:"` = either substring
    selected = [m for m in MUTATIONS if not wanted or any(w in m[0] for w in wanted)]
    stale = [f"{rel}: {name}" for name, rel, old, _new, _needs in selected
             if len(pattern_for(old).findall((ROOT / rel).read_text())) != 1]
    if stale:
        print("ERROR  these mutation anchors no longer match exactly once (code changed?):\n  " +
              "\n  ".join(stale))
        return 2

    if args.check:
        print(f"all {len(selected)} mutation anchors match exactly once")
        return 0

    survivors = []
    ran = 0
    for name, rel, old, new, needs in selected:
        preset = needs or args.preset
        path = ROOT / rel
        original = path.read_text()
        pat = pattern_for(old)
        if len(pat.findall(original)) != 1:
            print(f"ERROR  mutation target not found exactly once in {rel}: {name}")
            return 2
        ran += 1
        backup = BACKUP_DIR / rel
        backup.parent.mkdir(parents=True, exist_ok=True)
        backup.write_text(original)
        try:
            path.write_text(pat.sub(lambda _m: new, original, count=1))
            build = run(["cmake", "--build", "--preset", preset])
            if build.returncode != 0:
                # A mutant that does not compile proves nothing about the tests: fix the mutant.
                tail = (build.stderr or build.stdout)[-300:]
                print(f"INVALID   [{preset}] mutant does not build: {name}\n    {tail!r}")
                survivors.append(name + " (invalid mutant)")
                continue
            # A mutant can make a test hang or crawl (a join that loses its hash keys, a pool that
            # never wakes): a test that runs far past its normal time counts as failed.
            tests = run(["ctest", "--preset", preset, "-j8", "--stop-on-failure",
                         "--timeout", str(TEST_TIMEOUT_SECONDS)])
            if tests.returncode != 0:
                failed = [l.strip() for l in tests.stdout.splitlines() if "***Failed" in l
                          or "***Exception" in l or "***Timeout" in l
                          or "Subprocess aborted" in l][:2]
                print(f"killed    [{preset}] {name}\n          by: {failed}")
            else:
                print(f"SURVIVED  [{preset}] {name}")
                survivors.append(name)
        finally:
            path.write_text(original)
            backup.unlink(missing_ok=True)

    # Integrity check: every mutated file must be exactly as we found it.
    damaged = [f for f in targets() if (ROOT / f).read_text() != snapshot[f]]
    if damaged:
        print("FATAL: files differ from their original content after the run: " + ", ".join(damaged))
        return 3

    # leave the build directories consistent with the restored sources
    for preset in {args.preset, "asan", "tsan"}:
        run(["cmake", "--build", "--preset", preset])

    print(f"\n{ran - len(survivors)}/{ran} mutations killed")
    return 1 if survivors else 0


if __name__ == "__main__":
    sys.exit(main())
